---
include:
  - board: seeeduino_xiao_ble
    shield: MKB_L_Base MKB_L_JOY rgbled_adapter nice_oled
    snippet: Default zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_L_MODULE_JOY

  - board: seeeduino_xiao_ble
    shield: MKB_L_Base MKB_L_KEY rgbled_adapter nice_oled
    snippet: Default zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_L_MODULE_KEY

  - board: seeeduino_xiao_ble
    shield: MKB_R_Base MKB_R_TB rgbled_adapter nice_oled
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_R_MODULE_TBv4

  - board: seeeduino_xiao_ble
    shield: settings_reset
